### ISSUE TITLE
Erro de caso de uso E4

### ISSUE THREAD

**Issue by VitorAcosta** [VitorAcosta/Sistema-de-Judocas#1]
O **Caso de Uso E4 - Adicionar Professor** apresenta erros nos seguintes pontos:

## Problema 1
**Defeito de Requisito: Fato Incorreto** 

O passo 3 do Fluxo de Eventos (fluxo principal) diz que:
> "O sistema exibe a tela de cadastro de professores"

   Entretanto, nenhuma tela é mostrada, somente um _pop-up_ com dois botões de decisão.

**Demonstração:** 
![Captura de tela de 2022-06-03 19-05-04](https://user-images.githubusercontent.com/55991392/171964023-93ddce6a-ff34-43c7-a392-655da530636a.png)

## Problema 2
O passo 4 do Fluxo de Eventos (fluxo principal) diz:
> "Se o Professor já tem registro no Sistema como Aluno"

O correto não seria "Se o Professor já tem registro no Sistema"? 
Uma vez que, da maneira que está escrito, um aluno pode tornar-se professor.

## Problema 3

Existe um fluxo alternativo dentro do fluxo principal, a saber, o ponto 4. Seria um erro de descrição de caso de uso?

## Considerações

Com base nesses pontos, tomei a liberdade de escrever uma proposta de correção, conforme a imagem abaixo:

![PropostaE4](https://user-images.githubusercontent.com/55991392/171965314-f71cacab-c7bd-452f-aac6-eb014d766f19.png)

**Comment by Andy-Barbosa** [comment]
**Alterado o fluxo principal e alternativo do Caso de Uso E4.**

- O bloco 4 virou fluxo alternativo como citado no problema 3.
- O fluxo 3 foi alterado considerando o pop-up como comentado no problema 1.
  - Consequentemente o problema 2 foi resolvido.

Todas essas alterações foram dadas na revisão [04ca6cf](https://github.com/VitorAcosta/Sistema-de-Judocas/wiki/Casos-de-Uso/04ca6cf586f721b90401b48b3bcdfd887fdd8929)
