### ISSUE TITLE
Erro de caso de uso E9

### ISSUE THREAD

**Issue by Andy-Barbosa** [VitorAcosta/Sistema-de-Judocas#2]
No caso de uso E9 - Atualizar entidade.

No fluxo de eventos passo 3 é dito que o secretário informa ao sistema o numero de registro da entidade a ser atualizada.

![image](https://user-images.githubusercontent.com/49701501/172029006-9b7203e9-6495-4d72-b369-ea7c2c0111d4.png)

Porém, na imagem acima, mostra que a tela de atualização não pede numero de registro.

**Comment by VitorAcosta** [comment]
Caso de uso E9 foi alterado para corrigir a diferença entre o que foi especificado originalmente e o que o _software_ apresentou.

A revisão [89a5dbe](https://github.com/VitorAcosta/Sistema-de-Judocas/wiki/Casos-de-Uso/89a5dbe9ae11a7a57efd598fc3fb3f8c5c6e64ad) resolve essa issue.
