### ISSUE TITLE
Erro de caso de uso E9

### ISSUE THREAD

**Issue by Andy-Barbosa** [VitorAcosta/Sistema-de-Judocas#3]
Em continuação a issue https://github.com/VitorAcosta/Sistema-de-Judocas/issues/2#issue-1260915463.

O fluxo alternativo 3.a nunca será alcançado, pois ele se baseia no numero de registro de entidade.

**Comment by VitorAcosta** [comment]
Caso de uso E9 foi alterado para corrigir a diferença entre o que foi especificado originalmente e o que o _software_ apresentou.

Como a correção já compreendeu o erro citado, a revisão [89a5dbe](https://github.com/VitorAcosta/Sistema-de-Judocas/wiki/Casos-de-Uso/89a5dbe9ae11a7a57efd598fc3fb3f8c5c6e64ad) também resolve essa issue.
